question_new:
  pattern:  /question
  defaults: { _controller: PrestaAskeetBundle:Question:new }
  requirements:
    _method:  GET
  
question_create:
  pattern:  /question
  defaults: { _controller: PrestaAskeetBundle:Question:new }
  requirements:
    _method:  POST
  
question_view:
  pattern:  /question/{id}/view.html
  defaults: { _controller: PrestaAskeetBundle:Question:view }
  
  
answer_new:
  pattern:  /answer/{id_question}
  defaults: { _controller: PrestaAskeetBundle:Answer:new }
  requirements:
    _method:  GET
  
answer_create:
  pattern:  /answer/{id_question}
  defaults: { _controller: PrestaAskeetBundle:Answer:new }
  requirements:
    _method:  POST
    
    
  
user_new:
  pattern:  /user
  defaults: { _controller: PrestaAskeetBundle:User:new }
  requirements:
    _method:  GET
  
user_create:
  pattern:  /user
  defaults: { _controller: PrestaAskeetBundle:User:new }
  requirements:
    _method:  POST
  
user_success:
  pattern:  /user/success
  defaults: { _controller: PrestaAskeetBundle:User:success }
