parameters:
#    presta_askeet.example.class: Presta\AskeetBundle\Example

services:
#    presta_askeet.example:
#        class: %presta_askeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
