<?php

namespace Presta\AskeetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
	public function findAllJoinedToUser()
	{
		$query = $this->getEntityManager()
		->createQuery('
	            SELECT q, u FROM PrestaAskeetBundle:Question q
	            JOIN q.user u'
		);
	
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
	
	public function findOneByIdJoinedToOther($id)
	{
	    $query = $this->getEntityManager()
	        ->createQuery('
	            SELECT q, u, a FROM PrestaAskeetBundle:Question q
	            JOIN q.user u
	            JOIN q.answers a
	            WHERE q.id = :id'
	        )->setParameter('id', $id);
	
	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
	
}